[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
gig_basic_contract = "2up6Coari5SuDz8bWaLDLdmZCREwKVztoXVNcDx8Dg29"

[programs.localnet]
gig_basic_contract = "2up6Coari5SuDz8bWaLDLdmZCREwKVztoXVNcDx8Dg29"

[programs.mainnet]
gig_basic_contract = "2up6Coari5SuDz8bWaLDLdmZCREwKVztoXVNcDx8Dg29"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/god/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
