[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
gig_basic_contract = "BccHg9A6gnaC9a9NWinzqE6r7491ohyFaHWjFeYFxsBV"

[programs.localnet]
gig_basic_contract = "BccHg9A6gnaC9a9NWinzqE6r7491ohyFaHWjFeYFxsBV"

[programs.mainnet]
gig_basic_contract = "BccHg9A6gnaC9a9NWinzqE6r7491ohyFaHWjFeYFxsBV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "/home/god/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
